/**
 * Datos maestros extraídos de la base de datos actual para Seeding profesional.
 */
module.exports = {
  CATEGORIAS: [
    "Analgésicos",
    "Antibióticos",
    "Antiinflamatorios",
    "Vitaminas",
    "Dermatológicos",
    "Respiratorios",
    "Antivirales",
    "Insumos Medicos",
    "Estatinas",
    "Antibacteriano",
    "Accesorios de bebe",
    "Antihistaminicos",
    "Cosmeticos",
    "Precion Arterial",
    "IBP",
    "Anticonceptivos",
    "PDE5"
  ],
  LABORATORIOS: [
    { "nombre": "GENFAR", "pais": "Colombia" },
    { "nombre": "PHARMABRAND", "pais": "Ecuador" },
    { "nombre": "GRUPO DIFARE", "pais": "Ecuador" },
    { "nombre": "BAYER", "pais": "Alemania" },
    { "nombre": "PFIZER", "pais": "USA" },
    { "nombre": "BAGÓ", "pais": "Argentina" },
    { "nombre": "Caplin Point", "pais": "India" },
    { "nombre": "Sin Laboratorio", "pais": "Ecuador" },
    { "nombre": "Portugal", "pais": "Peru" },
    { "nombre": "ROEMMERS S.A.I.C", "pais": "Argentina" }
  ],
  PROVEEDORES: [
    {
      "ID": 5,
      "Nombre Empresa": "Agroproductos del Sur Cía. Ltda.",
      "RUC": "190045678001",
      "Dirección": "Calle Simón Bolívar 202",
      "Teléfono Empresa": "0983360275",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Luisa Ortega",
      "Cargo Contacto": "Jefa de Logística",
      "Teléfono Contacto": "965432110",
      "Email Contacto": "ventas@agrosur.ec"
    },
    {
      "ID": 12,
      "Nombre Empresa": "Alimentos Naturales del Ecuador Cía. Ltda.",
      "RUC": "1790112345001",
      "Dirección": "Avenida Eloy Alfaro 222",
      "Teléfono Empresa": "0983360276",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Ricardo Solís",
      "Cargo Contacto": "Supervisor de Calidad",
      "Teléfono Contacto": "9987654335",
      "Email Contacto": "ventas@alimentosnaturales.ec"
    },
    {
      "ID": 18,
      "Nombre Empresa": "Confecciones Moda Sur Cía. Ltda.",
      "RUC": "190178901001",
      "Dirección": "Avenida Solano 777",
      "Teléfono Empresa": "0983360277",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Rodrigo Valdez",
      "Cargo Contacto": "Diseñador de Producto",
      "Teléfono Contacto": "932109872",
      "Email Contacto": "contacto@modasur.ec"
    },
    {
      "ID": 4,
      "Nombre Empresa": "Construcciones Andinas ECU S.A.",
      "RUC": "190034567001",
      "Dirección": "Avenida 12 de Octubre 888",
      "Teléfono Empresa": "0983360278",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Diego Morales",
      "Cargo Contacto": "Ingeniero Residente",
      "Teléfono Contacto": "976543211",
      "Email Contacto": "info@construccionesandinas.ec"
    },
    {
      "ID": 20,
      "Nombre Empresa": "Consultoría Empresarial Andina S.A.",
      "RUC": "1790190123001",
      "Dirección": "Avenida 6 de Diciembre 909",
      "Teléfono Empresa": "0983360279",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Eduardo Sánchez",
      "Cargo Contacto": "Consultor Senior",
      "Teléfono Contacto": "910987652",
      "Email Contacto": "contacto@consultoriaandina.ec"
    },
    {
      "ID": 1,
      "Nombre Empresa": "DISMAG S.A",
      "RUC": "17109712336",
      "Dirección": "Av Granados y las Hiedras",
      "Teléfono Empresa": "0983360280",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Adriana Perez",
      "Cargo Contacto": "Vendedora Corporativa",
      "Teléfono Contacto": "982356987",
      "Email Contacto": "aperez@dismagcorp.com.ec"
    },
    {
      "ID": 3,
      "Nombre Empresa": "Distribuidora Comercial Guayaquil S.A.",
      "RUC": "990012345001",
      "Dirección": "Calle Sucre 123",
      "Teléfono Empresa": "0983360281",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Carlos Jiménez",
      "Cargo Contacto": "Coordinador de Ventas",
      "Teléfono Contacto": "991234568",
      "Email Contacto": "ventas@distribuidoragye.ec"
    },
    {
      "ID": 19,
      "Nombre Empresa": "Empaques Ecológicos Ecuador S.A.",
      "RUC": "990189012001",
      "Dirección": "Avenida Portugal 112",
      "Teléfono Empresa": "0983360282",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Nathalia Bravo",
      "Cargo Contacto": "Jefa de Desarrollo",
      "Teléfono Contacto": "921098762",
      "Email Contacto": "info@empaqueseco.ec"
    },
    {
      "ID": 7,
      "Nombre Empresa": "Ferretería Integral Ambato S.A.",
      "RUC": "1890067890001",
      "Dirección": "Avenida Juan Montalvo 111",
      "Teléfono Empresa": "0983360283",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Rosa Maldonado",
      "Cargo Contacto": "Vendedora Corporativa",
      "Teléfono Contacto": "943210988",
      "Email Contacto": "ventas@ferreteriaambato.ec"
    },
    {
      "ID": 11,
      "Nombre Empresa": "Importadora del Pacífico ECU S.A.",
      "RUC": "990101234001",
      "Dirección": "Avenida 9 de Octubre 777",
      "Teléfono Empresa": "0983360284",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Vanessa León",
      "Cargo Contacto": "Asistente de Compras",
      "Teléfono Contacto": "909876544",
      "Email Contacto": "info@importadorapacifico.ec"
    },
    {
      "ID": 2,
      "Nombre Empresa": "Insumos Industriales del Ecuador S.A.",
      "RUC": "1790023456001",
      "Dirección": "Avenida Amazonas N34-56",
      "Teléfono Empresa": "0983360285",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "María Fernanda Ruiz",
      "Cargo Contacto": "Gerente Comercial",
      "Teléfono Contacto": "987654322",
      "Email Contacto": "contacto@insumosindustriales.ec"
    },
    {
      "ID": 15,
      "Nombre Empresa": "Laboratorios BioSalud Cía. Ltda.",
      "RUC": "190145678001",
      "Dirección": "Calle Gran Colombia 101",
      "Teléfono Empresa": "0983360286",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Paulina Núñez",
      "Cargo Contacto": "Analista de Laboratorio",
      "Teléfono Contacto": "965432102",
      "Email Contacto": "contacto@biosalud.ec"
    },
    {
      "ID": 9,
      "Nombre Empresa": "Maquinarias Pesadas del Oriente S.A.",
      "RUC": "1790089012001",
      "Dirección": "Calle Napo 555",
      "Teléfono Empresa": "0983360287",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Gabriela Vargas",
      "Cargo Contacto": "Asistente Administrativa",
      "Teléfono Contacto": "921098766",
      "Email Contacto": "ventas@maquinariasorientales.ec"
    },
    {
      "ID": 14,
      "Nombre Empresa": "Papelera Nacional ECU S.A.",
      "RUC": "1790134567001",
      "Dirección": "Avenida Colón 606",
      "Teléfono Empresa": "0983360288",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Mauricio Delgado",
      "Cargo Contacto": "Ejecutivo de Cuentas",
      "Teléfono Contacto": "976543213",
      "Email Contacto": "ventas@papeleranacional.ec"
    },
    {
      "ID": 17,
      "Nombre Empresa": "Productos Químicos del Ecuador S.A.",
      "RUC": "1790167890001",
      "Dirección": "Avenida Morán Valverde 500",
      "Teléfono Empresa": "0983360289",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Claudia Peña",
      "Cargo Contacto": "Representante Técnico",
      "Teléfono Contacto": "943210982",
      "Email Contacto": "ventas@quimicosec.com.ec"
    },
    {
      "ID": 8,
      "Nombre Empresa": "Servicios Eléctricos del Litoral Cía. Ltda.",
      "RUC": "990078901001",
      "Dirección": "Avenida Malecón Simón Bolívar",
      "Teléfono Empresa": "0983360290",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Andrés Castro",
      "Cargo Contacto": "Técnico Instalador",
      "Teléfono Contacto": "932109877",
      "Email Contacto": "info@electrolitoral.ec"
    },
    {
      "ID": 16,
      "Nombre Empresa": "Servicios de Limpieza Urbana S.A.",
      "RUC": "1890156789001",
      "Dirección": "Avenida Olmedo 333",
      "Teléfono Empresa": "0983360291",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Jorge Almeida",
      "Cargo Contacto": "Encargado de Operaciones",
      "Teléfono Contacto": "954321092",
      "Email Contacto": "info@limpurbana.ec"
    },
    {
      "ID": 6,
      "Nombre Empresa": "Tecnología Aplicada Ecuador S.A.",
      "RUC": "1790056789001",
      "Dirección": "Avenida Río Coca 450",
      "Teléfono Empresa": "0983360292",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Javier Paredes",
      "Cargo Contacto": "Especialista Técnico",
      "Teléfono Contacto": "954321099",
      "Email Contacto": "contacto@techaplicada.ec"
    },
    {
      "ID": 21,
      "Nombre Empresa": "Tecnología en Redes del Ecuador Cía. Ltda.",
      "RUC": "990201234001",
      "Dirección": "Calle 10 de Agosto 404",
      "Teléfono Empresa": "0983360293",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Sofía Méndez",
      "Cargo Contacto": "Ingeniera de Sistemas",
      "Teléfono Contacto": "909876542",
      "Email Contacto": "soporte@tecred.ec"
    },
    {
      "ID": 10,
      "Nombre Empresa": "Textiles Ecuatorianos S.A.",
      "RUC": "190090123001",
      "Dirección": "Avenida Loja 300",
      "Teléfono Empresa": "0983360294",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Fernando Quintero",
      "Cargo Contacto": "Gerente de Producción",
      "Teléfono Contacto": "910987655",
      "Email Contacto": "contacto@textilesec.com.ec"
    },
    {
      "ID": 13,
      "Nombre Empresa": "Transportes Express Ecuador S.A.",
      "RUC": "990123456001",
      "Dirección": "Calle Benjamín Carrión 444",
      "Teléfono Empresa": "0983360295",
      "Email Empresa": "ventas@generico.com.ec",
      "Contacto": "Diana Mora",
      "Cargo Contacto": "Coordinadora de Rutas",
      "Teléfono Contacto": "987654324",
      "Email Contacto": "logistica@transexpress.ec"
    }
  ],
  PRODUCTOS: [
    {
      "nombreComercial": "3-DERMICO 30 G",
      "principioActivo": "Betametasona",
      "presentacion": "tubo de 30gr",
      "precioVenta": 4.29,
      "ultimoPrecioCompra": 2.2,
      "stockMinimo": 10,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Dermatológicos",
      "laboratorio": "BAYER"
    },
    {
      "nombreComercial": "ACICLOVIR 400MG",
      "principioActivo": "Aciclovir",
      "presentacion": null,
      "precioVenta": 21,
      "ultimoPrecioCompra": 4.8,
      "stockMinimo": 5,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antivirales",
      "laboratorio": "Caplin Point"
    },
    {
      "nombreComercial": "AMBROXOL JBE 15MG/5ML",
      "principioActivo": "Ambroxol",
      "presentacion": null,
      "precioVenta": 2.85,
      "ultimoPrecioCompra": 1.95,
      "stockMinimo": 15,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antibióticos",
      "laboratorio": "Portugal"
    },
    {
      "nombreComercial": "AMOXICILINA 500MG",
      "principioActivo": "Amoxicilina",
      "presentacion": "Caja x 100 tabletas",
      "precioVenta": 23,
      "precioVentaUnidad": 0.30,
      "unidadesPorCaja": 100,
      "ultimoPrecioCompra": 10.5,
      "stockMinimo": 8,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antibióticos",
      "laboratorio": "Caplin Point"
    },
    {
      "nombreComercial": "ARCODEX 120MG",
      "principioActivo": "Dexketoprofeno",
      "presentacion": null,
      "precioVenta": 18.5,
      "ultimoPrecioCompra": 5.77,
      "stockMinimo": 10,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antiinflamatorios",
      "laboratorio": "Portugal"
    },
    {
      "nombreComercial": "ASPIRINA ADVAN SOB",
      "principioActivo": "Ácido acetilsalicílico",
      "presentacion": null,
      "precioVenta": 12.3,
      "ultimoPrecioCompra": 9.47,
      "stockMinimo": 20,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Analgésicos",
      "laboratorio": "BAYER"
    },
    {
      "nombreComercial": "ATORVASTATINA 20 MG",
      "principioActivo": "Atorvastatina",
      "presentacion": null,
      "precioVenta": 33.6,
      "ultimoPrecioCompra": 5.15,
      "stockMinimo": 5,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Estatinas",
      "laboratorio": "Caplin Point"
    },
    {
      "nombreComercial": "AXIL CEFUROXIMA 500MG",
      "principioActivo": "Cefuroxima",
      "presentacion": null,
      "precioVenta": 18.12,
      "ultimoPrecioCompra": 9.85,
      "stockMinimo": 6,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antibióticos",
      "laboratorio": "GENFAR"
    },
    {
      "nombreComercial": "AZITROMICINA 500MG",
      "principioActivo": "Azitromicina",
      "presentacion": null,
      "precioVenta": 190,
      "ultimoPrecioCompra": 35.5,
      "stockMinimo": 3,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antibióticos",
      "laboratorio": "Portugal"
    },
    {
      "nombreComercial": "BACTRIPHARM FORTE",
      "principioActivo": "Sulfametoxazol + Trimetoprima",
      "presentacion": null,
      "precioVenta": 3.5,
      "ultimoPrecioCompra": 1.86,
      "stockMinimo": 25,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antibacteriano",
      "laboratorio": "BAGÓ"
    },
    {
      "nombreComercial": "BETAMETASONA FOSFATO SODICO",
      "principioActivo": "Betametasona",
      "presentacion": null,
      "precioVenta": 15,
      "ultimoPrecioCompra": 6.75,
      "stockMinimo": 10,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antiinflamatorios",
      "laboratorio": "Caplin Point"
    },
    {
      "nombreComercial": "CEFALEXINA CAP 500MG",
      "principioActivo": "Cefalexina",
      "presentacion": null,
      "precioVenta": 5.8,
      "ultimoPrecioCompra": 3.99,
      "stockMinimo": 12,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antibacteriano",
      "laboratorio": "Portugal"
    },
    {
      "nombreComercial": "CETIRIZINA TAB 10MG",
      "principioActivo": "Cetirizina",
      "presentacion": null,
      "precioVenta": 17,
      "ultimoPrecioCompra": 4.15,
      "stockMinimo": 10,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antihistaminicos",
      "laboratorio": "GENFAR"
    },
    {
      "nombreComercial": "CIPROFLOXACINA TAB REC",
      "principioActivo": "Ciprofloxacina",
      "presentacion": null,
      "precioVenta": 89,
      "ultimoPrecioCompra": 9.25,
      "stockMinimo": 4,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antibióticos",
      "laboratorio": "BAYER"
    },
    {
      "nombreComercial": "CLAVUXIDAN SUSP 312.5",
      "principioActivo": "Amoxicilina + Ácido clavulánico",
      "presentacion": null,
      "precioVenta": 10.8,
      "ultimoPrecioCompra": 6.23,
      "stockMinimo": 12,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antibióticos",
      "laboratorio": "ROEMMERS S.A.I.C"
    },
    {
      "nombreComercial": "COMPLEJO B CAPSULAS",
      "principioActivo": "Complejo B",
      "presentacion": null,
      "precioVenta": 5,
      "ultimoPrecioCompra": 2.45,
      "stockMinimo": 20,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Vitaminas",
      "laboratorio": "PFIZER"
    },
    {
      "nombreComercial": "DEXAMETASONA FOSFATO SODICO",
      "principioActivo": "Dexametasona",
      "presentacion": null,
      "precioVenta": 3.6,
      "ultimoPrecioCompra": 2.7,
      "stockMinimo": 15,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antiinflamatorios",
      "laboratorio": "PFIZER"
    },
    {
      "nombreComercial": "DICLO AZUL",
      "principioActivo": "Diclofenaco",
      "presentacion": null,
      "precioVenta": 14.1,
      "ultimoPrecioCompra": 5.7,
      "stockMinimo": 10,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antiinflamatorios",
      "laboratorio": "Caplin Point"
    },
    {
      "nombreComercial": "IBUPROFENO 600MG",
      "principioActivo": "Ibuprofeno",
      "presentacion": null,
      "precioVenta": 13,
      "ultimoPrecioCompra": 4.9,
      "stockMinimo": 8,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antiinflamatorios",
      "laboratorio": "Caplin Point"
    },
    {
      "nombreComercial": "LOSARTAN TAB 50MG",
      "principioActivo": "Losartán",
      "presentacion": null,
      "precioVenta": 38,
      "ultimoPrecioCompra": 6.84,
      "stockMinimo": 6,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Precion Arterial",
      "laboratorio": "GENFAR"
    },
    {
      "nombreComercial": "OMEPRAZOL 20MG",
      "principioActivo": "Omeprazol",
      "presentacion": null,
      "precioVenta": 3.05,
      "ultimoPrecioCompra": 1.2,
      "stockMinimo": 15,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "IBP",
      "laboratorio": "Portugal"
    },
    {
      "nombreComercial": "PARACETAMOL 500MG",
      "principioActivo": "Paracetamol",
      "presentacion": "Caja x 100 tabletas",
      "precioVenta": 5,
      "precioVentaUnidad": 0.10,
      "unidadesPorCaja": 100,
      "ultimoPrecioCompra": 2.2,
      "stockMinimo": 20,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Analgésicos",
      "laboratorio": "GENFAR"
    },
    {
      "nombreComercial": "PREDNISONA 20MG",
      "principioActivo": "Prednisona",
      "presentacion": null,
      "precioVenta": 45,
      "ultimoPrecioCompra": 11.15,
      "stockMinimo": 5,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Antiinflamatorios",
      "laboratorio": "GENFAR"
    },
    {
      "nombreComercial": "SILDENAFILO 100MG",
      "principioActivo": "Sildenafil",
      "presentacion": null,
      "precioVenta": 10,
      "ultimoPrecioCompra": 1.95,
      "stockMinimo": 10,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "PDE5",
      "laboratorio": "PFIZER"
    },
    {
      "nombreComercial": "T-BRAX 500",
      "principioActivo": "Ácido mefenámico",
      "presentacion": null,
      "precioVenta": 8.8,
      "ultimoPrecioCompra": 4.48,
      "stockMinimo": 12,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Analgésicos",
      "laboratorio": "Portugal"
    },
    {
      "nombreComercial": "AEROCAMARAS CARLITOS CLASICO ADULTO",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 9.88,
      "ultimoPrecioCompra": 10.868,
      "stockMinimo": 10,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "AGUJA DESCARTABLE 21G 1-1/4",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 3.13,
      "ultimoPrecioCompra": 3.443,
      "stockMinimo": 50,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "ALGODON FARMACOTON 100 GR",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 2.18,
      "ultimoPrecioCompra": 2.398,
      "stockMinimo": 30,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "BAJALENGUA HERENCO",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 1.96,
      "ultimoPrecioCompra": 2.156,
      "stockMinimo": 100,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "BIBERON CARLITOS 5 OZ",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 1.86,
      "ultimoPrecioCompra": 2.046,
      "stockMinimo": 20,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Accesorios de bebe",
      "laboratorio": null
    },
    {
      "nombreComercial": "CEPILLO DENTAL CARLITOS CLASICO",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 7.7,
      "ultimoPrecioCompra": 8.47,
      "stockMinimo": 40,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Accesorios de bebe",
      "laboratorio": null
    },
    {
      "nombreComercial": "CHINESCOS CARLITOS",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 1.46,
      "ultimoPrecioCompra": 1.606,
      "stockMinimo": 50,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Accesorios de bebe",
      "laboratorio": null
    },
    {
      "nombreComercial": "DISCOS DESMAQUILLANTES X50",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 1.54,
      "ultimoPrecioCompra": 1.694,
      "stockMinimo": 30,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Cosmeticos",
      "laboratorio": null
    },
    {
      "nombreComercial": "EQUIPO VENOCLISIS AZUL",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 0.45,
      "ultimoPrecioCompra": 0.495,
      "stockMinimo": 200,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "ESPARDRAPO 2.5 CM X 1 M",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 4.44,
      "ultimoPrecioCompra": 4.884,
      "stockMinimo": 25,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "FUNDA RECOLECTORA ORINA NIÑO",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 0.22,
      "ultimoPrecioCompra": 0.242,
      "stockMinimo": 100,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "GASA ESTERIL 10X10 CM",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 6.32,
      "ultimoPrecioCompra": 6.952,
      "stockMinimo": 60,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "GUANTE NITRILO MEDIUM",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 4.95,
      "ultimoPrecioCompra": 5.445,
      "stockMinimo": 100,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "HISOPO MADERA X100",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 0.71,
      "ultimoPrecioCompra": 0.781,
      "stockMinimo": 200,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "JERINGA 10 ML",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 9.57,
      "ultimoPrecioCompra": 10.527,
      "stockMinimo": 80,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "JERINGA INSULINA 1ML",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 8.84,
      "ultimoPrecioCompra": 9.724,
      "stockMinimo": 50,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "LANCETAS 28G",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 2.23,
      "ultimoPrecioCompra": 2.453,
      "stockMinimo": 100,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "MASCARILLA NEBULIZADOR ADULTO",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 1.74,
      "ultimoPrecioCompra": 1.914,
      "stockMinimo": 30,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "PRESERVATIVO SURE X72",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 8.94,
      "ultimoPrecioCompra": 9.834,
      "stockMinimo": 20,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Anticonceptivos",
      "laboratorio": "BAYER"
    },
    {
      "nombreComercial": "PRUEBA EMBARAZO SAFE TEST",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 2.7,
      "ultimoPrecioCompra": 2.97,
      "stockMinimo": 15,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Anticonceptivos",
      "laboratorio": "GRUPO DIFARE"
    },
    {
      "nombreComercial": "TERMOMETRO DIGITAL CARLITOS",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 2.36,
      "ultimoPrecioCompra": 2.596,
      "stockMinimo": 25,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Accesorios de bebe",
      "laboratorio": null
    },
    {
      "nombreComercial": "TETINA RN 0-6 MESES",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 0.55,
      "ultimoPrecioCompra": 0.605,
      "stockMinimo": 100,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Accesorios de bebe",
      "laboratorio": null
    },
    {
      "nombreComercial": "VENDA GASA 3\"",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 0.55,
      "ultimoPrecioCompra": 0.605,
      "stockMinimo": 50,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "VENDA TELA 4\"",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 1.36,
      "ultimoPrecioCompra": 1.496,
      "stockMinimo": 40,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    },
    {
      "nombreComercial": "VENDA HERENCO ELASTICA 6\"",
      "principioActivo": "-",
      "presentacion": null,
      "precioVenta": 1.17,
      "ultimoPrecioCompra": 1.287,
      "stockMinimo": 30,
      "requiereReceta": 0,
      "esControlado": 0,
      "categoria": "Insumos Medicos",
      "laboratorio": null
    }
  ]
};

